[package]
name = "mvc"
version = "0.0.2"
edition = "2024"

[dependencies]
serde = {version = "1.0.228", features=["derive"]}
serde_json = "1.0.149"
tar = "0.4.44"
sha2 = "0.10"
walkdir = "2.5.0"
colored = "3.1.1"
